# Generated by Django 2.2.4 on 2020-06-02 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_aliases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prerequisitedata',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_prerequisites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alias',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_aliases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prerequisitedata',
            name='child_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_dataset_as_child', to='tree.Course'),
        ),
        migrations.AlterField(
            model_name='prerequisitedata',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_prerequisites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prerequisitedata',
            name='parent_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_dataset_as_parent', to='tree.Course'),
        ),
    ]
