# Generated by Django 2.2.4 on 2020-06-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20200602_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name_plural': 'Aliases'},
        ),
        migrations.AlterModelOptions(
            name='prerequisitedata',
            options={'verbose_name_plural': 'Prerequisite Dataset'},
        ),
    ]
