# Generated by Django 2.2.4 on 2020-06-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20200602_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_number',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='ZZ000', max_length=20),
            preserve_default=False,
        ),
    ]
