# Generated by Django 2.2.4 on 2020-06-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20200602_1147'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prerequisitedata',
            constraint=models.UniqueConstraint(fields=('parent_course', 'child_course'), name='unique_prerequisite_data'),
        ),
    ]
