# Generated by Django 2.2.4 on 2020-06-02 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20200602_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_aliases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prerequisitedata',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_prerequisites', to=settings.AUTH_USER_MODEL),
        ),
    ]
