# Generated by Django 2.2.4 on 2020-06-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_auto_20200602_1211'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(fields=('full_name', 'course'), name='unique_alias_for_course'),
        ),
    ]
