# Generated by Django 2.2.4 on 2020-06-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_auto_20200602_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alias',
            name='author',
        ),
        migrations.RemoveField(
            model_name='alias',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='prerequisitedata',
            name='author',
        ),
        migrations.RemoveField(
            model_name='prerequisitedata',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='alias',
            name='num_likes',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prerequisitedata',
            name='num_likes',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
